### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by keybreak** [unixfox/nitter-fork#1]
I take it that's the new home and one that powers xcancel.com?
Works great so far! :+1: 

Any chance of getting working RSS in future? :smiley: 

So far it's
> URL is not a valid feed and contains no feed links.

**Comment by unixfox** [comment]
Yes please send an email rss [AT] xcancel [DOT] com.

Includes as much details as possible like the rss reader used, ip address and an example request.

**Comment by keybreak** [comment]
@unixfox 
Sorry, i'd rather not send IP and other stuff.

But rest of the info:
- Arch Linux
- Firefox / LibreWolf
- [FeedBro](https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/) rss reader
- Any xcancel RSS url you're trying to add, for example let it be: https://xcancel.com/elonmusk/rss
-  Doesn't matter if it's clear-net IP, vpn or Tor network - reader just don't see valid feed (i assume because of the cull down period?).

**Comment by unixfox** [comment]
Please send an email. This GitHub issue tracker is for bugs related to this nitter fork.
