### ISSUE TITLE
Rate limited for new test account

### ISSUE THREAD

**Issue by pnikhil610** [unixfox/nitter-fork#2]
Hi @unixfox,
I tried to setup a nitter instance.
I had created a test account on x.com and applied for developer portal free tier access.
I used the access_token and access_token_secret from there in guest_accounts.json file.
But as soon as the service is up and running, I am getting rate limit exceeded error.

Your help is highly appreciated.
Thanks

**Comment by unixfox** [comment]
I don't give any helps. Use the nitter matrix room.
