### ISSUE TITLE
Media stops loading after a while 

### ISSUE THREAD

**Issue by CanadianBaconeer** [unixfox/nitter-fork#5]
After browsing for a while media stops loading; videos don't play and clicking on images that loaded before returns a "503 service temporarily unavailable" error. This isn't an issue I've experienced with any other Nitter instances so far (though I avoid using these due to issues they suffer from that xcancel doesn't). I've only found one temporary fix: use a VPN and switch to another IP address.
![IMG_5804](https://github.com/user-attachments/assets/42acb91c-9b00-4561-b107-8cff092a10d3)
![IMG_5803](https://github.com/user-attachments/assets/b252a222-2cce-48ca-a31f-1bf7e9a3b7d1)

**Comment by unixfox** [comment]
Hello, xcancel is meant to be used occasionally on some x/twitter posts and it not meant for heavy usage like the real X/Twitter.

I can look into increasing the rate limit for medias. But ultimately this may lead to the cost of more abuse from bots.

If you like nitter I would suggest to host one yourself: https://github.com/sekai-soft/guide-nitter-self-hosting

I have plans to improve the case by removing the rate limit but I haven't had the time yet.

**Comment by unixfox** [comment]
has been fixed
